require("nvim-plugins.telescope")
require("nvim-plugins.colorizer")
require("nvim-plugins.compe")
require("nvim-plugins.treesitter")
require("nvim-plugins.galaxyline")
require("nvim-plugins.bufferline")
require("nvim-plugins.tsrainbow")
-- require("nvim-plugins.gitsigns")
require("nvim-plugins.autopairs")
require("nvim-plugins.neogit")
require("nvim-plugins.lightbulb")
