require("nvim-plugins.telescope")
require("nvim-plugins.colorizer")
require("nvim-plugins.compe")
require("nvim-plugins.treesitter")
require("nvim-plugins.bufferline")
require("nvim-plugins.rainbow")
require("nvim-plugins.autopairs")
require("nvim-plugins.neogit")
require("nvim-plugins.kommentary")
require("nvim-plugins.lualine")
require("nvim-plugins.gitsigns")
require("nvim-plugins.lightbulb")
require("nvim-plugins.fterm")
-- require("nvim-plugins.toggleterm")
-- require("nvim-plugins.revj")

