-- normal nvim
require("plugins")
require("global")
require("keybindings")
require("settings")
require("variables")
require("lsp")
require("dbg")
require("aucommands")
require("masoninstaller")
require("myplugins")
require("colorscheme")
