require('Comment').setup()

vim.filetype.add({ extension = { wgsl = "wgsl" } })

vim.g.mapleader = ","
vim.o.clipboard = "unnamedplus"

vim.cmd("noremap <expr> k (v:count > 5 ? \"m'\" . v:count : \"\") . 'k'")
vim.cmd("noremap <expr> j (v:count > 5 ? \"m'\" . v:count : \"\") . 'j'")
vim.keymap.set("i", ".", ".<c-g>u", { noremap = true })
vim.keymap.set("i", ",", ",<c-g>u", { noremap = true })
vim.keymap.set("i", "(", "(<c-g>u", { noremap = true })
vim.keymap.set("i", "{", "{<c-g>u", { noremap = true })
vim.keymap.set("i", "\"", "\"<c-g>u", { noremap = true })
vim.keymap.set("i", "'", "'<c-g>u", { noremap = true })
vim.keymap.set("i", ":", ":<c-g>u", { noremap = true })
vim.keymap.set("i", "<", "<<c-g>u", { noremap = true })
vim.keymap.set("i", "<c-c>", "<esc>", { noremap = true })
vim.keymap.set("i", "jk", "<esc>", { noremap = true })
vim.keymap.set("i", "jj", "<esc>", { noremap = true })
vim.keymap.set("t", "<esc>", "<C-\\><C-n>", { noremap = true })
--
-- -- CORE KEYBINDINGS
vim.keymap.set("n", "q:", "<nop>", { noremap = true })
vim.keymap.set("n", "Y", "y$", { noremap = true })
vim.keymap.set("n", "#", "#zz", { noremap = true })
vim.keymap.set("n", "*", "*zz", { noremap = true })
vim.keymap.set("n", "<c-u>", "<c-u>zz", { noremap = true })
vim.keymap.set("n", "<c-d>", "<c-d>zz", { noremap = true })
vim.keymap.set("n", "n", "nzzzv", { noremap = true })
vim.keymap.set("n", "N", "Nzzzv", { noremap = true })
vim.keymap.set("n", "J", "mzJ`z", { noremap = true })
vim.keymap.set("n", "zh", "35zh", { noremap = true })
vim.keymap.set("n", "zl", "35zl", { noremap = true })
vim.keymap.set("v", ">", ">gv", { noremap = true })
vim.keymap.set("v", "<", "<gv", { noremap = true })
vim.keymap.set("v", "m", ">gv", { noremap = true })
vim.keymap.set("v", "n", "<gv", { noremap = true })

vim.keymap.set('x', 'K', ':move \'<-2<cr>gv-gv', { noremap = true })
vim.keymap.set('x', 'J', ':move \'>+1<cr>gv-gv', { noremap = true })

vim.keymap.set("n", "<space>a", "ggVG", { noremap = true })
vim.keymap.set("n", "<space>d", "<cmd>call VSCodeCall('workbench.action.closeActiveEditor')<cr>", { noremap = true })
vim.keymap.set("n", "<space>bo", "<cmd>call VSCodeCall('workbench.action.closeOtherEditors')<cr>", { noremap = true })
vim.keymap.set("n", "<space>w", "<cmd>call VSCodeCall('workbench.action.files.saveFiles')<cr>", { noremap = true })

vim.keymap.set("n", "<space>ss", "<cmd>call VSCodeCall('search.action.openEditor')<cr>", { noremap = true })
-- vim.keymap.set("n", "<space>sn", "<cmd>call VSCodeCall('search.action.focusNextSearchResult')<cr>", { noremap = true })
-- vim.keymap.set("n", "<space>sp", "<cmd>call VSCodeCall('search.action.focusPreviousSearchResult')<cr>", { noremap = true })
-- vim.keymap.set("n", "<space>sw", "<cmd>call VSCodeCall('search.action.focusSearchFromResults')<cr>", { noremap = true })
vim.keymap.set("n", "<space>sq", "<cmd>call VSCodeCall('search.action.focusQueryEditorWidget')<cr>", { noremap = true })
vim.keymap.set("n", "<space>si", "<cmd>call VSCodeCall('search.action.focusFilesToInclude')<cr>", { noremap = true })
vim.keymap.set("n", "<space>so", "<cmd>call VSCodeCall('search.action.focusFilesToExclude')<cr>", { noremap = true })

vim.keymap.set("n", "<leader>n", "<cmd>call VSCodeCall('workbench.files.action.showActiveFileInExplorer')<cr>", { noremap = true })
vim.keymap.set({ "n", "v" }, "m,", "<cmd>call VSCodeCall('bookmarks.toggle')<cr>", { noremap = true })
vim.keymap.set({ "n", "v" }, "m.", "<cmd>call VSCodeCall('bookmarks.list')<cr>", { noremap = true })
vim.keymap.set({ "n", "v" }, "<space>tm", "<cmd>call VSCodeCall('bookmarks.listFromAllFiles')<cr>", { noremap = true })

vim.keymap.set({ "n", "v" }, "<leader>.", "<cmd>HopAnywhere<cr>", { noremap = true })
vim.keymap.set({ "n", "v" }, "<leader>m", "<cmd>HopWord<cr>", { noremap = true })
vim.keymap.set({ "n", "v" }, "<leader>pw", "<cmd>HopWord<cr>", { noremap = true })
vim.keymap.set({ "n", "v" }, "<leader>ps", "<cmd>HopLineStart<cr>", { noremap = true })
vim.keymap.set({ "n", "v" }, "<leader>pl", "<cmd>HopLine<cr>", { noremap = true })
vim.keymap.set({ "n", "v" }, "<leader>pp", "<cmd>HopPattern<cr>", { noremap = true })
vim.keymap.set({ "n", "v" }, "<leader>pc", "<cmd>HopChar2<cr>", { noremap = true })
vim.keymap.set({ "n", "v" }, "<leader>pC", "<cmd>HopChar1<cr>", { noremap = true })
vim.keymap.set({ "n", "v" }, "<leader>pC", "<cmd>HopChar1<cr>", { noremap = true })
