-- require('lsp.rust_analyzer')
require('lsp.rust_tools')
require('lsp.pylsp')
-- require('lsp.sumneko')
-- require('lsp.flow')
require('lsp.tsserver')
require('lsp.clangd')
require('lsp.html')
require('lsp.jsonls')

